apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ansible-subscription
  namespace: argocd
  annotations:
    apps.open-cluster-management.io/git-branch: rhconnect
    apps.open-cluster-management.io/git-path: gitops-manifests/resources/prod
    apps.open-cluster-management.io/reconcile-option: replace
  labels:
    app: argocd
    app.kubernetes.io/part-of: argocd
prehooks:
  - apiVersion: tower.ansible.com/v1alpha1
    kind: AnsibleJob
    metadata:
      name: slack-notification
      namespace: argocd
      annotations: {}
      labels:
        app.kubernetes.io/name: argocd
      ownerReferences:
        - name: ansible-subscription-1
          apiVersion: apps.open-cluster-management.io/v1
          kind: Subscription
    spec:
      extra_vars:
      job_template_name: demojobtemplate
      tower_auth_secret: admin-token
spec:
  channel: channel-openshift-gitops
  hooksecretref:
    name: admin-token
  placement:
    placementRef:
      name: openshift-gitops-placementrule
      kind: PlacementRule