bases:
  - ../../base/
  - policy/

resources:
  - OpenshiftGitopsPlacementrule.yaml
  - OpenshiftGitopsAppsSubscription.yaml
  - OpenshiftGitopsSubscription.yaml
  - policy/Placementbinding-openshift-gitops.yaml
  - policy/PolicyOpenshiftGitops.yaml