bases:
  - ../../base/
  - policy/

resources:
  - ApplicationOpenshiftGitops.yaml
  - OpenshiftGitopsPlacementrule.yaml
  - OpenshiftGitopsAppsSubscription.yaml
  - OpenshiftGitopsSubscription.yaml
  - AnsibleJobSubscription.yaml
