apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-placementrule
  namespace: openshift-gitops
  labels:
    app: argocd
spec:
  clusterConditions:
    matchExpressions:
    - key: role
      operator: In
      values:
      - rhconnect1
    matchLabels: {}
  clusterReplicas: 1